name: UI Patterns Settings
type: module
description: Configure patterns with settings
package: User interface
core_version_requirement: ^8 || ^9
dependencies:
  - ui_patterns:ui_patterns
  - token:token

# Information added by Drupal.org packaging script on 2022-09-29
version: '8.x-2.0-beta16'
project: 'ui_patterns_settings'
datestamp: 1664462566
